"""little changes made

Revision ID: 14666e947a67
Revises: 
Create Date: 2022-11-15 16:57:43.050640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14666e947a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('name_db', sa.String(length=40), nullable=False))
    op.add_column('item', sa.Column('price_db', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('barcode_db', sa.String(), nullable=False))
    op.add_column('item', sa.Column('description_db', sa.String(length=1024), nullable=False))
    op.create_unique_constraint(None, 'item', ['barcode_db'])
    op.create_unique_constraint(None, 'item', ['name_db'])
    op.drop_column('item', 'name')
    op.drop_column('item', 'barcode')
    op.drop_column('item', 'description')
    op.drop_column('item', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.INTEGER(), nullable=False))
    op.add_column('item', sa.Column('description', sa.VARCHAR(length=1024), nullable=False))
    op.add_column('item', sa.Column('barcode', sa.VARCHAR(), nullable=False))
    op.add_column('item', sa.Column('name', sa.VARCHAR(length=40), nullable=False))
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'description_db')
    op.drop_column('item', 'barcode_db')
    op.drop_column('item', 'price_db')
    op.drop_column('item', 'name_db')
    # ### end Alembic commands ###
